# Install script for directory: /Users/reemalattas/Downloads/joints-3/Demos

# Set the install prefix
if(NOT DEFINED CMAKE_INSTALL_PREFIX)
  set(CMAKE_INSTALL_PREFIX "/usr/local")
endif()
string(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
if(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)
  if(BUILD_TYPE)
    string(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  else()
    set(CMAKE_INSTALL_CONFIG_NAME "Release")
  endif()
  message(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
endif()

# Set the component getting installed.
if(NOT CMAKE_INSTALL_COMPONENT)
  if(COMPONENT)
    message(STATUS "Install component: \"${COMPONENT}\"")
    set(CMAKE_INSTALL_COMPONENT "${COMPONENT}")
  else()
    set(CMAKE_INSTALL_COMPONENT)
  endif()
endif()

if(NOT CMAKE_INSTALL_LOCAL_ONLY)
  # Include the install script for each subdirectory.
  include("/Users/reemalattas/Downloads/joints-3/Demos/HelloWorld/cmake_install.cmake")
  include("/Users/reemalattas/Downloads/joints-3/Demos/MultiThreadedDemo/cmake_install.cmake")
  include("/Users/reemalattas/Downloads/joints-3/Demos/OpenCLClothDemo/cmake_install.cmake")
  include("/Users/reemalattas/Downloads/joints-3/Demos/OpenGL/cmake_install.cmake")
  include("/Users/reemalattas/Downloads/joints-3/Demos/AllBulletDemos/cmake_install.cmake")
  include("/Users/reemalattas/Downloads/joints-3/Demos/ConvexDecompositionDemo/cmake_install.cmake")
  include("/Users/reemalattas/Downloads/joints-3/Demos/CcdPhysicsDemo/cmake_install.cmake")
  include("/Users/reemalattas/Downloads/joints-3/Demos/BulletXmlImportDemo/cmake_install.cmake")
  include("/Users/reemalattas/Downloads/joints-3/Demos/ConstraintDemo/cmake_install.cmake")
  include("/Users/reemalattas/Downloads/joints-3/Demos/SliderConstraintDemo/cmake_install.cmake")
  include("/Users/reemalattas/Downloads/joints-3/Demos/GenericJointDemo/cmake_install.cmake")
  include("/Users/reemalattas/Downloads/joints-3/Demos/Raytracer/cmake_install.cmake")
  include("/Users/reemalattas/Downloads/joints-3/Demos/RagdollDemo/cmake_install.cmake")
  include("/Users/reemalattas/Downloads/joints-3/Demos/ForkLiftDemo/cmake_install.cmake")
  include("/Users/reemalattas/Downloads/joints-3/Demos/BasicDemo/cmake_install.cmake")
  include("/Users/reemalattas/Downloads/joints-3/Demos/FeatherstoneMultiBodyDemo/cmake_install.cmake")
  include("/Users/reemalattas/Downloads/joints-3/Demos/RollingFrictionDemo/cmake_install.cmake")
  include("/Users/reemalattas/Downloads/joints-3/Demos/RaytestDemo/cmake_install.cmake")
  include("/Users/reemalattas/Downloads/joints-3/Demos/VoronoiFractureDemo/cmake_install.cmake")
  include("/Users/reemalattas/Downloads/joints-3/Demos/GyroscopicDemo/cmake_install.cmake")
  include("/Users/reemalattas/Downloads/joints-3/Demos/FractureDemo/cmake_install.cmake")
  include("/Users/reemalattas/Downloads/joints-3/Demos/Box2dDemo/cmake_install.cmake")
  include("/Users/reemalattas/Downloads/joints-3/Demos/BspDemo/cmake_install.cmake")
  include("/Users/reemalattas/Downloads/joints-3/Demos/MovingConcaveDemo/cmake_install.cmake")
  include("/Users/reemalattas/Downloads/joints-3/Demos/VehicleDemo/cmake_install.cmake")
  include("/Users/reemalattas/Downloads/joints-3/Demos/UserCollisionAlgorithm/cmake_install.cmake")
  include("/Users/reemalattas/Downloads/joints-3/Demos/CharacterDemo/cmake_install.cmake")
  include("/Users/reemalattas/Downloads/joints-3/Demos/SoftDemo/cmake_install.cmake")
  include("/Users/reemalattas/Downloads/joints-3/Demos/CollisionInterfaceDemo/cmake_install.cmake")
  include("/Users/reemalattas/Downloads/joints-3/Demos/ConcaveConvexcastDemo/cmake_install.cmake")
  include("/Users/reemalattas/Downloads/joints-3/Demos/SimplexDemo/cmake_install.cmake")
  include("/Users/reemalattas/Downloads/joints-3/Demos/DynamicControlDemo/cmake_install.cmake")
  include("/Users/reemalattas/Downloads/joints-3/Demos/ConvexHullDistance/cmake_install.cmake")
  include("/Users/reemalattas/Downloads/joints-3/Demos/DoublePrecisionDemo/cmake_install.cmake")
  include("/Users/reemalattas/Downloads/joints-3/Demos/ConcaveDemo/cmake_install.cmake")
  include("/Users/reemalattas/Downloads/joints-3/Demos/CollisionDemo/cmake_install.cmake")
  include("/Users/reemalattas/Downloads/joints-3/Demos/ContinuousConvexCollision/cmake_install.cmake")
  include("/Users/reemalattas/Downloads/joints-3/Demos/ConcaveRaycastDemo/cmake_install.cmake")
  include("/Users/reemalattas/Downloads/joints-3/Demos/GjkConvexCastDemo/cmake_install.cmake")
  include("/Users/reemalattas/Downloads/joints-3/Demos/MultiMaterialDemo/cmake_install.cmake")
  include("/Users/reemalattas/Downloads/joints-3/Demos/SerializeDemo/cmake_install.cmake")
  include("/Users/reemalattas/Downloads/joints-3/Demos/InternalEdgeDemo/cmake_install.cmake")
  include("/Users/reemalattas/Downloads/joints-3/Demos/Benchmarks/cmake_install.cmake")
  include("/Users/reemalattas/Downloads/joints-3/Demos/ThreadingDemo/cmake_install.cmake")
  include("/Users/reemalattas/Downloads/joints-3/Demos/VectorAdd_OpenCL/cmake_install.cmake")

endif()

